title:             dkdk Blog
email:             dkdkernel@gmail.com
description:       dkdk blog
author:            dkdk
baseurl:           "/"
url:               "https://dankernel.github.io/"

# Social Profiles
twitter_username:  SBootstrap
github_username:   BlackrockDigital
facebook_username: StartBootstrap

# Build settings
markdown:          kramdown
paginate:          5
paginate_path:     "/posts/page:num/"
plugins:
  - jekyll-feed
  - jekyll-paginate
